cabal-version: 3.0
name:          hott
version:       0.0.0
category:      Language

common settings
  default-language:   GHC2021
  default-extensions:
    NoImplicitPrelude
    BlockArguments
    DataKinds
    DefaultSignatures
    DerivingStrategies
    DuplicateRecordFields
    FunctionalDependencies
    LambdaCase
    MultiWayIf
    OverloadedRecordDot
    OverloadedStrings
    PatternSynonyms
    QuasiQuotes
    RecordWildCards
    TypeFamilies
    ViewPatterns

  build-depends:
    , base  >=4.17
    , mtl
    , parsec >= 3.1.17
    , parser-combinators
    , text  >=2.0

  ghc-options:        -Wall -Wno-unticked-promoted-constructors

library
  import:          settings
  hs-source-dirs:  lib
  exposed-modules:
    Language.Hott.Source
    Language.Hott.Syntax
